import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import {
  INITIAL_CANDIDATE_MASK,
  REGISTERED_PREDICATES,
  previewDisclosure,
  serializeMask,
} from '../../../packages/game-engine/src/index';
import {
  CASE_CANDIDATE_COUNT,
  CERTIFIED_DISCLOSURE_LIMIT,
  MINIMUM_SURVIVING_CANDIDATES,
} from '../../../packages/protocol/src/index';
import { expect, it } from 'vitest';

it('generates Move and JSON vectors from the canonical B2 engine', async () => {
  const dimensionOrder = ['suspect', 'room', 'weapon', 'time'] as const;
  const dimensionCounts = new Map<string, number>();
  const predicates = REGISTERED_PREDICATES.map((predicate, numericId) => {
    const dimensionId = dimensionOrder.indexOf(predicate.dimension);
    expect(dimensionId).toBeGreaterThanOrEqual(0);
    const valueIndex = dimensionCounts.get(predicate.dimension) ?? 0;
    dimensionCounts.set(predicate.dimension, valueIndex + 1);
    const preview = previewDisclosure(INITIAL_CANDIDATE_MASK, predicate);
    return {
      numericId,
      browserId: predicate.id,
      dimension: predicate.dimension,
      dimensionId,
      valueId: predicate.valueId,
      valueIndex,
      mask: serializeMask(predicate.truthMask),
      maskDecimal: predicate.truthMask.toString(),
      yesInitialCount: preview.yesCandidateCount,
      noInitialCount: preview.noCandidateCount,
    };
  });

  expect(predicates).toHaveLength(12);
  const vectors = {
    generatedFrom: '@alibi/game-engine',
    schemaVersion: 1,
    caseCount: CASE_CANDIDATE_COUNT,
    predicateCount: predicates.length,
    initialCandidateMask: serializeMask(INITIAL_CANDIDATE_MASK),
    disclosureLimit: CERTIFIED_DISCLOSURE_LIMIT,
    minimumSurvivors: MINIMUM_SURVIVING_CANDIDATES,
    predicates: predicates.map(({ maskDecimal: _maskDecimal, ...predicate }) => predicate),
  };

  const root = fileURLToPath(new URL('..', import.meta.url));
  await mkdir(new URL('../test-vectors/', import.meta.url), { recursive: true });
  await writeFile(
    new URL('../test-vectors/predicates.json', import.meta.url),
    `${JSON.stringify(vectors, null, 2)}\n`,
  );

  const assertions = predicates
    .map(
      (predicate) =>
        `    assert_eq!(predicates::predicate_mask(${predicate.numericId}), ${predicate.maskDecimal}u64);\n` +
        `    let definition = predicates::definition(${predicate.numericId});\n` +
        `    assert_eq!(predicates::dimension(&definition), ${predicate.dimensionId});\n` +
        `    assert_eq!(predicates::value(&definition), ${predicate.valueIndex});`,
    )
    .join('\n');
  const generatedMove = `// Generated by contracts/alibi/scripts/generate-predicate-vectors.test.ts. Do not edit.\n#[test_only]\nmodule alibi::generated_predicate_vectors;\n\nuse std::unit_test::assert_eq;\nuse alibi::predicates;\n\n#[test]\nfun move_predicates_match_b2_generated_vectors() {\n    assert_eq!(predicates::case_count(), ${CASE_CANDIDATE_COUNT});\n    assert_eq!(predicates::count(), ${predicates.length});\n    assert_eq!(predicates::universe_mask(), ${INITIAL_CANDIDATE_MASK.toString()}u64);\n${assertions}\n}\n`;
  await writeFile(new URL('../tests/generated_predicate_vectors.move', import.meta.url), generatedMove);
  console.log(`Generated ${predicates.length} predicate vectors under ${root}`);
});