// Generated by contracts/alibi/scripts/generate-predicate-vectors.test.ts. Do not edit.
#[test_only]
module alibi::generated_predicate_vectors;

use std::unit_test::assert_eq;
use alibi::predicates;

#[test]
fun move_predicates_match_b2_generated_vectors() {
    assert_eq!(predicates::case_count(), 64);
    assert_eq!(predicates::count(), 12);
    assert_eq!(predicates::universe_mask(), 18446744073709551615u64);
    assert_eq!(predicates::predicate_mask(0), 65535u64);
    let definition = predicates::definition(0);
    assert_eq!(predicates::dimension(&definition), 0);
    assert_eq!(predicates::value(&definition), 0);
    assert_eq!(predicates::predicate_mask(1), 4294901760u64);
    let definition = predicates::definition(1);
    assert_eq!(predicates::dimension(&definition), 0);
    assert_eq!(predicates::value(&definition), 1);
    assert_eq!(predicates::predicate_mask(2), 281470681743360u64);
    let definition = predicates::definition(2);
    assert_eq!(predicates::dimension(&definition), 0);
    assert_eq!(predicates::value(&definition), 2);
    assert_eq!(predicates::predicate_mask(3), 18446462598732840960u64);
    let definition = predicates::definition(3);
    assert_eq!(predicates::dimension(&definition), 0);
    assert_eq!(predicates::value(&definition), 3);
    assert_eq!(predicates::predicate_mask(4), 4222189076152335u64);
    let definition = predicates::definition(4);
    assert_eq!(predicates::dimension(&definition), 1);
    assert_eq!(predicates::value(&definition), 0);
    assert_eq!(predicates::predicate_mask(5), 67555025218437360u64);
    let definition = predicates::definition(5);
    assert_eq!(predicates::dimension(&definition), 1);
    assert_eq!(predicates::value(&definition), 1);
    assert_eq!(predicates::predicate_mask(6), 1080880403494997760u64);
    let definition = predicates::definition(6);
    assert_eq!(predicates::dimension(&definition), 1);
    assert_eq!(predicates::value(&definition), 2);
    assert_eq!(predicates::predicate_mask(7), 17294086455919964160u64);
    let definition = predicates::definition(7);
    assert_eq!(predicates::dimension(&definition), 1);
    assert_eq!(predicates::value(&definition), 3);
    assert_eq!(predicates::predicate_mask(8), 3689348814741910323u64);
    let definition = predicates::definition(8);
    assert_eq!(predicates::dimension(&definition), 2);
    assert_eq!(predicates::value(&definition), 0);
    assert_eq!(predicates::predicate_mask(9), 14757395258967641292u64);
    let definition = predicates::definition(9);
    assert_eq!(predicates::dimension(&definition), 2);
    assert_eq!(predicates::value(&definition), 1);
    assert_eq!(predicates::predicate_mask(10), 6148914691236517205u64);
    let definition = predicates::definition(10);
    assert_eq!(predicates::dimension(&definition), 3);
    assert_eq!(predicates::value(&definition), 0);
    assert_eq!(predicates::predicate_mask(11), 12297829382473034410u64);
    let definition = predicates::definition(11);
    assert_eq!(predicates::dimension(&definition), 3);
    assert_eq!(predicates::value(&definition), 1);
}
